config/routes.rb
Rails.application.routes.draw do
  get '/' => 'books#top', as: 'root'
  get 'books' => 'books#index'
  get 'books' => 'books#new'
  post 'books' => 'books#create'
  get 'books/:id' => 'books#show', as: 'book'
  delete 'books/:id' => 'books#destroy', as: 'destroy_book'
  get 'books/:id/edit' => 'books#edit', as: 'edit_book'
  patch 'books/:id' => 'books#update'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def top
  end

  def index
    @books = Book.all
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path,notice:'Book was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path,notice:'Book was successfully destroyed.'
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
        redirect_to book_path(@book),notice:'Book was successfully created.'
    else
      @books = Book.all
      render :index
    end
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= form_for(@book, url:"/books/#{@book.id}") do |f| %>

<%= render 'layouts/error_messages' %>

  <div class="field">
    <h4>Title</h4>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <h4>Body</h4>
    <%= f.text_area :body %>
  </div>
    <div class ="action">
      <%= f.submit 'Update Book' %>
    </div>
<% end %>

<%= link_to "Show", book_path(@book) %>
|
<%= link_to "Back", books_path %>

app/views/books/index.html.erb
<p class="notice">
  <%= notice %>
</p>

<body>
  <h1>Books</h1>
  <table>
    <thead>
      <th class="table_title">Title</th>
      <th class="table_body">Body</th>
      <th></th>
    </thead>
    <tbody>
      <% @books.each do |book| %>
      <tr>
        <td class="table_title"><%= book.title %></td>
        <td class="table_body"><%= book.body %></td>
        <td><%= link_to "Show", book_path(book.id) %></td>
        <td><%= link_to "Edit", edit_book_path(book.id) %></td>
        <td><%= link_to "Destroy", destroy_book_path(book),method: :delete %></td>
      </tr>
      <% end %>
    </tbody>
  </table>

  <h2>New book</h2>
<%= form_for(@book) do |f| %>

  <%= render 'layouts/error_messages' %>

  <div class="field">
    <h4>Title</h4>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <h4>Body</h4>
    <%= f.text_area :body %>
  </div>
    <div>
      <%= f.submit 'Create Book' %>
    </div>
  <% end %>
</body>

app/views/books/show.html.erb
<p class="notice">
  <%= notice %>
</p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>
<p>
  <strong>Body:</strong>
  <%= @book.body %>
</p>

<%= link_to "Edit", edit_book_path(@book) %>
|
<%= link_to "Back", books_path %>

app/views/books/top.html.erb
<h1>ようこそ <strong>Bookers</strong> へ！</h1>
<p><strong>Bookers</strong> では、さまざまな書籍に関するあなたの意見や</p>
<p>印象を共有し交換することができます</p>

<P><%= link_to "start", books_path(@book) %></p>

app/views/layouts/_error_messages.html.erb
<% if @book.errors.any? %>
  <div class="alert alert-warning">
  <h2><%= @book.errors.count %> errors prohibited this obj from being saved:</h2>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>